### ISSUE TITLE
Expose performance data as Godot monitor

### ISSUE THREAD

**Issue by bitbrain** [utopia-rise/fmod-gdextension#146]
Godot supports In-Editor performance monitoring: https://docs.godotengine.org/en/latest/tutorials/scripting/debug/custom_performance_monitors.html

The idea is that we can track various metrics in Godot and it will be displayed inside the Monitors tab. Possible metrics we can track:

| Metric Name | Description |
|---|---|
| `fmod/cpu` | CPU usage |
| `fmod/memory/allocated` | Memory usage (allocated) |
| `fmod/file` | File usage |
| `fmod/listeners/total` | Number of total listeners |

Feel free to suggest additional metrics we could track!

**Comment by piiertho** [comment]
Can you check current master state, I added monitors.
