### ISSUE TITLE
Addon crashes when changing scenes (Godot 4 only)

### ISSUE THREAD

**Issue by bitbrain** [utopia-rise/fmod-gdextension#153]
**Godot version: 4.0.2**
**Addon version: 5baf5d86008e2aa9584261e9f518a689a6d488b5**

Changing scenes in Godot 4 is currently not quite working. There are two issues that I was able to reproduce in the demo project: https://github.com/utopia-rise/fmod-gdnative/tree/scene-change-crash

![fmod-bug-0](https://user-images.githubusercontent.com/822035/230910550-40926be4-414f-404d-be98-01fcc92e100b.PNG)

## Issue 1: changing to a different scene will crash the game silently

After some debugging it seems to happen inside `Fmod.update()` function. There are no logs as it simply crashes silently. Click the "Change to other scene" button on the branch linked above to reproduce!

## Issue 2: reloading the current scene will spam thousands of errors

When unloading and reloading the current scene instead, the game does not crash but thousands of errors are being produced over time.

![fmod-bug-1](https://user-images.githubusercontent.com/822035/230910376-52846f4b-4a88-405b-805f-e81ebea16119.PNG)

Click the "Reload current scene" button on the branch linked above to reproduce!

**Comment by piiertho** [comment]
Cannot reproduce with your branch.
