### ISSUE TITLE
Godot sometimes freezes when an Fmod event is created

### ISSUE THREAD

**Issue by Tombomhom** [utopia-rise/fmod-gdextension#158]
Hi,

We have been using fmod-gdnative for our game but sometimes the game will crash after triggering a sound. There's no real reason that we can discern, it just seems random. Have you experienced this before?

We even tried the demo out and the same problem occurred.

We added code to the FmodTest.gd script in the demo project to have the music event created and released quickly on repeat and there was no pattern to how long it took to crash.

This was the code we added:

func _ready():
	genNew()

func genNew():
	var id = Fmod.create_event_instance("event:/Music/Level 02")
	Fmod.start_event(id)
	Fmod.attach_instance_to_node(id, self)
	yield(get_tree().create_timer(0.3), "timeout")
	Fmod.detach_instance_from_node(id)
	Fmod.stop_event(id, Fmod.FMOD_STUDIO_STOP_IMMEDIATE)
	Fmod.release_event(id)
	genNew()
	
Is this a problem you have encountered before? Any help would be really appreciated!

We're using Godot Engine v3.5.2 and the FMOD API 2.02.09

**Comment by CedNaru** [comment]
Hello, 
that's not really a problem I am aware of. I have met a few issues that could happen when an instance is attached to an event and then the instance released before being detached, causing possibly some memory access error. But it seems your test is not released the instance anyway, so it can't be that.
Can you provide the error you can when it crashes ?

**Comment by Tombomhom** [comment]
Thanks for getting back so quick.

There is no information in the debugging panel when it freezes unfortunately. The scene just freezes and in my applications panel (I'm on mac) it says it's not responding, so I have to force quit. My friend uses windows and gets the same problem so It's not a mac thing.

**Comment by k-nacho** [comment]
@Tombomhom did you ever figured it out why this happens? I'm having the same issue as of today

**Comment by schweller** [comment]
@Tombomhom did you ever figure this out? I'm having the same, as of today 😢

**Comment by piiertho** [comment]
@schweller you have it with Godot 4 ?

**Comment by schweller** [comment]
@piiertho no! Godot 3.5 and the extension version is 3.2.0

**Comment by schweller** [comment]
Downgrading to the version just previously released worked for me! If someone is also stuck.
