### ISSUE TITLE
Unable to acces banks.

### ISSUE THREAD

**Issue by GinahePro** [utopia-rise/fmod-gdextension#179]
Hi there. Just discovered your addons. Tried to install it by following the docs but that is not working. My FmodExplorer don't show anything and I have these red error in the console when I start my godot.

./core/variant/variant_utility.cpp:905 - An invalid object handle was used.class godot::Ref<class godot::FmodBank> __cdecl godot::FmodCache::add_bank(const class godot::String &,unsigned int)src\fmod_cache.cpp47
  ./core/variant/variant_utility.cpp:905 - An invalid object handle was used.class godot::Ref<class godot::FmodBank> __cdecl godot::FmodCache::add_bank(const class godot::String &,unsigned int)src\fmod_cache.cpp47
  
  The issue only occur when I have my master in my bank folder.
  
  Using godot 4.1.3. If you have any advice.

**Comment by GinahePro** [comment]
Not working in 4.1.2 either.

**Comment by piiertho** [comment]
Hello ! Setup guide on doc is outdated, we need to update it.  
Please refer to readme for plugin installation. Then doc can be used for plugin configuration: https://fmod-gdextension.readthedocs.io/en/latest/user-guide/2-initialization/

**Comment by GinahePro** [comment]
Thx a lot . The issue was that it was not needed anymore to import your own version of FmodLib
