### ISSUE TITLE
Bank explorer does not refresh when updating .bank file

### ISSUE THREAD

**Issue by bitbrain** [utopia-rise/fmod-gdextension#180]
**Godot Version**: `4.1.2.stable`
**FMOD Studio Version**: `2.02.16`
**Addon Version**: `Release 4.0.1-4.1.2`

When doing changes to banks in FMOD and saving it, the .bank explorer inside Godot does not apply the changes.

## Steps to reproduce

1. create new event in FMOD
2. save the event and export .bank file
3. navigate to Fmod Explorer

**Expected behavior**: new event is displayed
**Actual behaviour**: new event is missing

**Comment by CedNaru** [comment]
Bank refresh is now available with #202
