### ISSUE TITLE
Is there a way to set an FMOD event parameter by label

### ISSUE THREAD

**Issue by RetroSpecter** [utopia-rise/fmod-gdextension#186]
Currently trying to set up FMOD music transitions through labels thought I am not sure how to do that here. 

Is there a method that I am missing, or if it is not implemented yet, a workaround to get it working?

below is the documentation from FMODs  Event Instance class (not sure if it is entirely 1 to 1 with this libraries FmodEvent class)
![image](https://github.com/utopia-rise/fmod-gdextension/assets/15240973/a16289c3-5b09-4fb1-b2a8-0aab326b30bd)

**Comment by MindlessRuff** [comment]
I'm new to using FMOD, but I was able to figure this out.

Here is my parameter with labels in FMOD (Note the column to the right where it says Value):

![image](https://github.com/utopia-rise/fmod-gdextension/assets/40220862/1d443b6e-a641-4f03-9bb1-4781d0d1ffaa)

In Godot, I created an enum to correspond to each label value like so:

`enum {MAIN_LOOP_INTRO, MAIN_LOOP_CURIOUS, MAIN_LOOP_EERIE, MAIN_LOOP_DRONE, MAIN_LOOP_GARBLED}`

Then I was able to set the parameter like this (you can do this at the Event level too):
`FmodServer.set_global_parameter_by_name("mainLoopLevel", MAIN_LOOP_CURIOUS)`

Hope that helps.

**Comment by rune-scape** [comment]
theres a missing method on FmodServer and FmodEvent :/

**Comment by rune-scape** [comment]
theres still a missing method by the same name in FmodServer, this should be reopened
