### ISSUE TITLE
Godot 4.2 - Could not find type "FmodNative"

### ISSUE THREAD

**Issue by fijaniques** [utopia-rise/fmod-gdextension#192]
Hi, couldn't find this issue anywhere, so i'm sorry if there is one

I'm using Godot 4.2, and in the Fmod.gd there is:

`godot_fmod: FmodNative`

But there's no such type as FmodNative

**Comment by bitbrain** [comment]
@fijaniques which addon version are you using?

**Comment by fijaniques** [comment]
I'm using the FMOD 2.02.17 for Godot 4.1.1 stable v1.0-alpha-4 , but I just saw this:

FMOD version 2.02.17 and Godot 4.1.1 stable are supported

I'm using godot 4.2

**Comment by CedNaru** [comment]
FmodNative is an old type that was used in the Godot 3.x release of the plugin. Are you sure you weren't missing new files ? Like updating the libraries but not the scripts inside the addon ?

**Comment by 3ter** [comment]
It seems pretty obvious that @fijaniques isn't using the current code version. @CedNaru Could you please close the issue to not repel users looking for an Fmod integration for the latest Godot 4 version?
