### ISSUE TITLE
Silent crash when using low level api for playing one shots on Linux

### ISSUE THREAD

**Issue by lentsius-bark** [utopia-rise/fmod-gdextension#199]
I am creating a game where I target windows and the **steamdeck**. Windows works fine and the later mentioned issues are specific to when playing the game on the steamdeck, hence the issue has been tested and observed on the device only, as I do not have access to a linux system.

I am using Godot 4.2.1.stable and the latest available official release of the gdextension plugin called [**Release 4.1.0 - 4.2.0**](https://github.com/utopia-rise/fmod-gdextension/releases/tag/4.1.0-4.2.0)

one_shot:
```swift
FmodServer.play_one_shot("event:/SFX/GridCellPressed", self)
```
results in an instant crash when the game tries playing that sound

one_shot_attached:
```swift
FmodServer.play_one_shot_attached("event:/SFX/GridCellPressed", self)
```
results in a crash right after the sound finishes playing.

in both scenarios I've also tried to replace `self` with `get_viewport().get_camera_3d()` and it hadn't helped.

edit:
also trying `play_one_shot_using_guid` and got an instant crash as well, before the sound started playing.

**Comment by CedNaru** [comment]
Fixed by #201
