### ISSUE TITLE
push_error: The requested event, parameter, bus or vca could not be found

### ISSUE THREAD

**Issue by the-old-one** [utopia-rise/fmod-gdextension#212]
When starting my game from the editor I'm getting the following errors. One for each bank, bus and event that I have in the project. After that the project works fine. What could be the issue?

Bank:
```
E 0:00:00:0818   push_error: The requested event, parameter, bus or vca could not be found.class godot::Ref<class godot::FmodBank> __cdecl godot::FmodBank::create_ref(class FMOD::Studio::Bank *)D:\a\fmod-gdextension\fmod-gdextension\src\studio/fmod_bank.h13
  <C++ Source>   core/variant/variant_utility.cpp:1091 @ push_error()
```
Bus:
```
E 0:00:00:0848   push_error: The requested event, parameter, bus or vca could not be found.class godot::Ref<class godot::FmodBus> __cdecl godot::FmodBus::create_ref(class FMOD::Studio::Bus *)D:\a\fmod-gdextension\fmod-gdextension\src\studio\fmod_bus.h9
  <C++ Source>   core/variant/variant_utility.cpp:1091 @ push_error()

```

**Comment by the-old-one** [comment]
I've found the issue. I needed to put `Master.strings.bank` before `Master.bank` in the BankLoader. I wonder why.

**Comment by 3ter** [comment]
I had the same issue and wondered why as well. If you gained some more insights I would be thankful if you could add them here: 
https://github.com/utopia-rise/fmod-gdextension/discussions/222

**Comment by brevven** [comment]
Ran into the same issue. Was getting VCA and event description parameter errors as well, they disappeared when I changed the order, too. It might be worth noting in the documentation that the `strings` bank should come first.
