### ISSUE TITLE
Cannot change parameters on FMOD events

### ISSUE THREAD

**Issue by Gaming-With-Portals** [utopia-rise/fmod-gdextension#217]
I can't figure out for the life of me why my events won't accept parameter changes, when I try to change parameters I get "The requested parameter, bus, or vca could not be found. 
This is my code:
![image](https://github.com/utopia-rise/fmod-gdextension/assets/73725114/95f2bfef-b242-481e-84c9-db8c0f062906)

This is how I am creating the event tracks:
![image](https://github.com/utopia-rise/fmod-gdextension/assets/73725114/38880931-7bff-4ce5-98e0-3118852a1d4c)

Here are the parameters in FMOD: (And yes, these are applied to the event I am using them on)
![image](https://github.com/utopia-rise/fmod-gdextension/assets/73725114/74879856-3995-455b-8546-06aad0c9d9a9)

Edit:
I realize some code is redundant, this is mostly an artifact of me trying a bunch of different solutions before asking this 

Any ideas?

**Comment by Gaming-With-Portals** [comment]
Update: I tried changing master.strings to load first, as that was a fix for a few other people, and now my game just crashes on load, it's a grey screen for a few seconds and then it just says --debugging stopped--

**Comment by piiertho** [comment]
> Update: I tried changing master.strings to load first, as that was a fix for a few other people, and now my game just crashes on load, it's a grey screen for a few seconds and then it just says --debugging stopped--

Hello ! Thanks for reporting.
Can you start engine from a terminal so we get more logs ?

**Comment by Gaming-With-Portals** [comment]
I don't have the logs, I was able to use a different extension to get it to work.
As far as I'm aware it was reporting nothing though, I assume it's just a driver conflict or something with my Audio API as I have a lot of custom stuff installed

**Comment by JamesK89** [comment]
I'm also having this issue. It does not matter if I set the parameter on the FmodEventEmitter3D object from the inspector, or if I set the parameter from code, it does not have any effect.

**Comment by piiertho** [comment]
> I'm also having this issue. It does not matter if I set the parameter on the FmodEventEmitter3D object from the inspector, or if I set the parameter from code, it does not have any effect.

Hello ! Did you loaded master bank first ?

**Comment by JamesK89** [comment]
> > I'm also having this issue. It does not matter if I set the parameter on the FmodEventEmitter3D object from the inspector, or if I set the parameter from code, it does not have any effect.
> 
> Hello ! Did you loaded master bank first ?

Yes, I loaded the master bank first. I also tried loading the master strings bank first as well, as an earlier comment mentioned, and it had no impact.

**Comment by JamesK89** [comment]
> Can you provide a minimal reproduction project ? So that I can have a look at it ? Cannot reproduce on our demo project

Here you go! I've removed the contents of the addons/fmod folder to reduce the file size of the attached archive, but I am using the latest release as of this writing (Release 4.3.0-4.2.2) so you should be able to just drop that in.

[fmoddemo.zip](https://github.com/user-attachments/files/16898886/fmoddemo.zip)

**Comment by Lvl50Hornist** [comment]
Im also having this issue, but not in the inspector, just with scripts.

**Comment by piiertho** [comment]
Hello !
@JamesK89 I just downloaded and imported your demo project in godot 4.3.
I cannot reproduce with it, sound is playing without any error logs:

https://github.com/user-attachments/assets/5af34c89-314e-4f88-8658-2cf042d714ce

**Comment by JamesK89** [comment]
> Hello !
> @JamesK89 I just downloaded and imported your demo project in godot 4.3.
> I cannot reproduce with it, sound is playing without any error logs:
> 
> https://github.com/user-attachments/assets/5af34c89-314e-4f88-8658-2cf042d714ce
> 
> 
> 

The second button is supposed to play a different sound based on a parameter, as @Dodoveloper noted.

**Comment by piiertho** [comment]
Ok I found why parameter has no effect.  
That's a design problem regarding how we load event.  
Preload event does not load the event. It will load it only when clicking play.  
If I change call of `preload_event` to `load_event` in `ready` method in `FmodEventEmitter` template, parameter is applied.
