### ISSUE TITLE
How to handle warning "No listeners are set!"

### ISSUE THREAD

**Issue by 3ter** [utopia-rise/fmod-gdextension#218]
I've added an `FmodListener2D` both to my `master` scene and to the `player` scene but still the error pops up when I change rooms (which doesn't free the `master` scene).

Original warning:
```
W 0:00:08:0021   FmodManager.gd:8 @ _process(): FMOD Sound System: No listeners are set!void __cdecl godot::FmodServer::_set_listener_attributes(void)src\fmod_server.cpp251
  <C++ Source>   core/variant/variant_utility.cpp:1111 @ push_warning()
  <Stack Trace>  FmodManager.gd:8 @ _process()
```

Please help me understand the concept better.

**Comment by piiertho** [comment]
Hello !
This means you don't have any listener set, or you don't have any valid node attached to listeners.
Can you provide your scene structure ?

**Comment by 3ter** [comment]
So I thought I'd only need a listener on the `player` (as it can move in the 2D space) but then the warning is triggered in the main menu (below UI in the screenshot) the first time.
![image](https://github.com/utopia-rise/fmod-gdextension/assets/11499929/8f540f61-2aab-45f0-8bf3-9f253c6419d4)
When the room is switched then (so `starting room` below is replaced by another one) the warning is triggered again.

**Comment by piiertho** [comment]
> So I thought I'd only need a listener on the `player` (as it can move in the 2D space) but then the warning is triggered in the main menu (below UI in the screenshot) the first time. ![image](https://private-user-images.githubusercontent.com/11499929/331868168-8f540f61-2aab-45f0-8bf3-9f253c6419d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjMwMDcsIm5iZiI6MTcxNjEyMjcwNywicGF0aCI6Ii8xMTQ5OTkyOS8zMzE4NjgxNjgtOGY1NDBmNjEtMmFhYi00NWYwLThiZjMtOWYyNTNjNjQxOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJjZGE5ZDNjMjQ2NWFkNmRiMmE1M2M3ZGQ4ZTg2NzdjOTU0NjZiZjE1OTVkMGRhNWJkMmMzZmQyYWIxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjzN6Xy9airdMdBoaMq_TZT8eyROr01YcGuMJsvNPq4) When the room is switched then (so `starting room` below is replaced by another one) the warning is triggered again.
> 
> EDIT: I just saw that there's a built-in `AudioListener2D` node. This has a `current` property to enable/disable it. Isn't this needed for the `FmodListener2D` as well? Or can you listen from multiple positions at once (sounds confusing... pun not intended).
> 
> I saw https://fmod-gdextension.readthedocs.io/en/latest/user-guide/3-nodes/#fmod-listeners, but it didn't really help there.

`AudioListener2D` has nothing to do with fmod, it comes from godot builtin sound engine.  
When you switch scene you don't have a listener set for few moment, so it will print the warn.  
It should stop printing it when you add back a listener.

**Comment by 3ter** [comment]
I do know that they are unrelated. I just had two `FmodListener2D` and wanted to know how they work together. It seems they don't.
- When I have 2 `FmodListener2D` the one attached to the player seems to take precedence (independend from the `index` setting on both nodes) and the warning is thrown on scene switch.
- When I only have 1 `FmodListener2D` attached to the `main` scene then no warnings are printed (but I suppose I loose the ability for spatial audio according to the player's position).

So I suppose I can only have one `FmodListener2D` in the scene tree at a given time and should reparent it from the `main` scene to the `player` when it's instantiated. Is that all correct?

Thanks a lot for your help so far, I do appreciate it!

**Comment by piiertho** [comment]
> I do know that they are unrelated. I just had two `FmodListener2D` and wanted to know how they work together. It seems they don't.
> 
> * When I have 2 `FmodListener2D` the one attached to the player seems to take precedence (independend from the `index` setting on both nodes) and the warning is thrown on scene switch.
> * When I only have 1 `FmodListener2D` attached to the `main` scene then no warnings are printed (but I suppose I loose the ability for spatial audio according to the player's position).
> 
> So I suppose I can only have one `FmodListener2D` in the scene tree at a given time and should reparent it from the `main` scene to the `player` when it's instantiated. Is that all correct?
> 
> Thanks a lot for your help so far, I do appreciate it!

You don't lose spatialisation with only one listener.  
If you want to setup more listeners you have to set listeners indexes in node, but you also have to change listener count in project settings:
![image](https://github.com/utopia-rise/fmod-gdextension/assets/48322356/7477df47-cb6a-4375-a30e-f0d99f1360d2)

**Comment by 3ter** [comment]
So for a scene change you recommend to reparent the same listener or attach a new one to a scene higher up in the hierarchy so there's always one listener available?

**Comment by piiertho** [comment]
> So for a scene change you recommend to reparent the same listener or attach a new one to a scene higher up in the hierarchy so there's always one listener available?

I think the warning is not important. Fmod will provide you a default listener without position until you re-add one.

**Comment by 3ter** [comment]
Even using `reparent()` the FMOD sound system emits this warning. I can't think of a way to get around it.
Thank you for your ongoing support. If you've got a project to share where it's done, I'd be happy to check it out 🙂 .

**Comment by 3ter** [comment]
Just wanted to add that I managed to get rid of the error by making sure the listener added to the main scene is only then freed, when there already is another one ready. The trick was to use the `tree_entered` signal accordingly.

```gdscript
func start_game() -> void:
	$BackgroundMusic.play()
	
	room_path_to_load = STARTING_ROOM
	spawn_point_to_load = STARTING_SPAWN_POINT
	on_current_room_freed()

	current_room.tree_entered.connect(on_starting_room_loaded)


func on_starting_room_loaded() -> void:
	$FmodListener2D.queue_free()
	room_changed.emit()
```
