### ISSUE TITLE
Warning message in Godot console [resource_format_text.cpp]

### ISSUE THREAD

**Issue by DevMimas** [utopia-rise/fmod-gdextension#228]
A yellow warning is displayed in the console. Fmod works so far.
The warning always appears when you restart Godot, so it is permanently displayed.

How do I get rid of the warning text?

```
Godot Engine v4.2.2.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  scene/resources/resource_format_text.cpp:448 - res://addons/fmod/tool/property_editors/FmodGuidAndPathPropertyEditorUi.tscn:4 - ext_resource, invalid UID: uid://dca7c6jnnpl0f - using text path instead: res://addons/fmod/icons/event_icon.svg
Autoload hinzufügen
```

Screenshot
![grafik](https://github.com/utopia-rise/fmod-gdextension/assets/44207756/1586af20-76b0-43cf-b478-08ef3c37886c)

**Comment by CedNaru** [comment]
It seems there is a mismatch between the UID declared in the scene:
https://github.com/utopia-rise/fmod-gdextension/blob/b878f5cfa385322bd2270272d31c0bc3520397dd/demo/addons/fmod/tool/property_editors/FmodGuidAndPathPropertyEditorUi.tscn#L4
and the actual resource UID:
https://github.com/utopia-rise/fmod-gdextension/blob/b878f5cfa385322bd2270272d31c0bc3520397dd/demo/addons/fmod/icons/event_icon.svg.import#L5.

It should be an easy fix.
On your side, you can simply open `addons/fmod/tool/property_editors/FmodGuidAndPathPropertyEditorUi.tscn` and save it again. It should automatically update the UID

**Comment by DevMimas** [comment]
Hi @CedNaru , thank you very much for your feedback and support.
I will install the new update. Hope that everything works then.
