### ISSUE TITLE
Support for discrete and labeled parameters

### ISSUE THREAD

**Issue by Dodoveloper** [utopia-rise/fmod-gdextension#233]
It would be nice to have an integrated way of knowing what kind of parameters an event has.

AFAIK, at the moment every parameter is treated as a `float`. This can work, but setting parameters in the inspector isn't exactly ideal and could easily lead to errors, as:
- I'm not sure what setting a **discrete** parameter to a float leads to (e.g. does it get rounded?)
- to properly set **labeled** parameters, one would have to always check the FMod project, which can be error prone

IMO, these are a big deal as a project gets bigger and bigger. Especially if you wanna have non-Godot devs working on setting up audio, say from the inspector.

I was wondering if adding this kind of support is something you guys are considering or not.

**Comment by piiertho** [comment]
Hello ! Yes we consider supporting those kind of arguments. It is just a matter of time.
