### ISSUE TITLE
OLD VERSION: Cannot put scripts onto FmodEventEmitter2D's that call the play() function. 

### ISSUE THREAD

**Issue by tot121212** [utopia-rise/fmod-gdextension#234]
Calling the play() function seemingly doesn't work if the nodes script is calling play() on itself
This could be fixed in newer versions but I am using https://github.com/utopia-rise/fmod-gdextension/tree/4.0.0-4.1.2

**Comment by CedNaru** [comment]
The EventEmitter has been heavily reworked in a recent version and I can confirm it works since then. We directly use `play()` in the 3D demo:
https://github.com/utopia-rise/fmod-gdextension/blob/b878f5cfa385322bd2270272d31c0bc3520397dd/demo/high_level_3D/environment/soundcollider.gd#L10
