### ISSUE TITLE
Truble obteining GUID from Event Name

### ISSUE THREAD

**Issue by MarioRibeHerrero** [utopia-rise/fmod-gdextension#258]
Currently using a nested dictionary to store the name along with the event name and the GUID, this would be avoided if I new the way to get the GUID using the event name.
```python
var music_sounds = {
	"MainTrack": {
		"event": "event:/MainTrack",
		"guid": "{16a1b6fa-aa97-4518-ad63-7d53f5e779a9}"
	}
}

## Then Getting the event and GUID this way
var guid = music_sounds[audio_name]["guid"]
var event = music_sounds[audio_name]["event"]
``` 
Any help appreciated

**Comment by CedNaru** [comment]
If you want to obtain the guid from an eventname, you can simply use an EventDescription instance (The bank containing that description must be loaded already):

```gdscript
var desc = Fmod.get_event("NameOfYourEvent")
var guid = desc.get_guid()
````

**Comment by MarioRibeHerrero** [comment]
Thank you for ur repply, cant seem to get the FmodEventDescription set, Fmod.get_event is a nonexistent funcition. What component is the Fmod??Should I be inhereting from an specific class?? Srry if I seem to noob, im new to godot :()
```
## This is not working
var desc = Fmod.get_event("NameOfYourEvent")
``` 
I have tryed getting the component from the bankloader but havent had any luck.

**Comment by CedNaru** [comment]
Sorry, I mistyped.

You are supposed to write `FmodServer.get_event`
