### ISSUE TITLE
C# support for fmod-extension

### ISSUE THREAD

**Issue by ilexl** [utopia-rise/fmod-gdextension#261]
For those who don't want to use GDScript, can someone help with a C# extension for fmod

**Comment by CedNaru** [comment]
Adding C# support can be done in 3 ways currently:
- Wait for Godot to add automatic C# binding generation based on the extensions in your project (So no change to that project would be required).
- Create manual C# wrappers around the current extension (using reflection based String calls to the current extension, terribly bothersome to do, unsafe and inefficient)
- Make the plugin natively C#. 

Honestly, we are very unlikely to do anything about it. Turning this plugin into C# is not an option for us, and we don't wish to do the same work a second time in a different language either.
Even if someone was willing to do, that would probably need to be its own separate project. Merging it here would just add extra workload for us maintainers (we struggle enough with that with just C++), so we are not ready to deal with it.

Anyway, feel free to use this issue (or our discord) if you want to find people that would be willing to do it. I personally don't have an issue with a conversation about being done here if it can help. Just know that the current maintainers of this repo won't contribute.
