### ISSUE TITLE
Error only sometimes happens on launch

### ISSUE THREAD

**Issue by ilexl** [utopia-rise/fmod-gdextension#267]
Randomly I when I run godot with this extension, and error will occur with the FmodManager.gd script
![image](https://github.com/user-attachments/assets/ed3fef70-da08-4896-a5eb-c1a28163e41c)
![image](https://github.com/user-attachments/assets/dc29f350-dc9d-4ff5-a5be-55a3649cf6c7)
In the logs FMOD Sound System did load correctly so im not sure where the error is coming from. Stopping and playing the project again works just fine. It will just do this every so often.
![image](https://github.com/user-attachments/assets/74cada7b-4d67-4c69-9f70-dffa96b0e6e8)

**Comment by CedNaru** [comment]
According to the PR I have seen for Godot 4.4, it should be resolved by then.
