### ISSUE TITLE
Reset to default Fmod banks on FmodBankLoader causes crash by playing any event, restarting the engine is needed

### ISSUE THREAD

**Issue by dalzott0** [utopia-rise/fmod-gdextension#278]
Add-on Version: Release 4.3.0-4.2.2
Engine: Godot v4.3.stable.official [77dcf97d8]
Running on Windows 11.

By resetting the banks list on the FmodBankLoader using the reset to default button glitches the node, and by trying to play any event crashes the game, restarting the engine is needed to fixed. I note that, the ( + ) and ( - ) buttons works fine for editing the Banks list.

![image](https://github.com/user-attachments/assets/b08dfc11-dde8-4c13-910d-e17e3f6512de)

https://github.com/user-attachments/assets/f9ee006b-3320-4e66-8a67-18b6e6804b61

On video, when I click on the reset to default button and set the bank again, the rest button not shows up, strange, but idk

**Comment by piiertho** [comment]
Which bank is originally loaded ?

**Comment by dalzott0** [comment]
The same bank selected the other times, bank:/Master.
