### ISSUE TITLE
FmodListener2D references get lost

### ISSUE THREAD

**Issue by timoschwarzer** [utopia-rise/fmod-gdextension#291]
I have set `default_listener_count` to 2 and added two FmodListener2D nodes to the tree. One of them has `listener_index = 0`, the other has `listener_index = 1`. Both of them have a weight of 0.5 and are not locked.

After some debugging, I noticed that `FmodServer.get_listener_transform2d(0)` always returns a zero transform.
`FmodServer.get_object_attached_to_listener(0)` returns some weird `[Wrapped:0]` object, and `FmodServer.get_object_attached_to_listener(1)` returns `<Object#null>`, so something seems to cause `listeners[i].gameObj` to become invalid.

Replacing these nodes with custom nodes and adding them manually using `FmodServer.add_listener(0, self)` in GDScript works.

Godot Version 4.4-dev
Addon Version: 5.0.0-4.3.0

**Comment by piiertho** [comment]
Hello ! Are those listeners added to the scene via the editors, or do you add them programmatically and then set their index ?

**Comment by timoschwarzer** [comment]
These are two `FmodListener2D` that are in the main scene. Both have set their index to 0 and 1 respectively.

**Comment by piiertho** [comment]
And you have set them using editor, right ?
